//Movie actions
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const RECEIVE_MOVIE_DETAILS = "RECEIVE_MOVIE_DETAILS";

//Movies actions
export const FETCH_MOVIES_IN_THEATRES = "FETCH_MOVIES_IN_THEATRES";
export const FETCH_MOVIES_POPULAR = "FETCH_MOVIES_POPULAR";
export const FETCH_MOVIES_UPCOMING = "FETCH_MOVIES_UPCOMING";
export const FETCH_MOVIES_TOP_RATED = "FETCH_MOVIES_TOP_RATED";

//TV Shows actions
export const FETCH_TV_SHOWS_ON_TV = "FETCH_TV_SHOWS_ON_TV";
export const FETCH_TV_SHOWS_POPULAR = "FETCH_TV_SHOWS_POPULAR";
export const FETCH_TV_SHOWS_AIRING_TODAY = "FETCH_TV_SHOWS_AIRING_TODAY";
export const FETCH_TV_SHOWS_TOP_RATED = "FETCH_TV_SHOWS_TOP_RATED";

//TV Show actions
export const FETCH_TV_SHOW_DETAILS = "FETCH_TV_SHOW_DETAILS";
export const RECEIVE_TV_SHOW_DETAILS = "RECEIVE_TV_SHOW_DETAILS";

//Window actions
export const UPDATE_COLUMNS_IN_ROW = "UPDATE_COLUMNS_IN_ROW";
export const DETECT_MOBILE = "DETECT_MOBILE";

//Discover actions
export const FETCH_DISCOVER_MOVIES = "FETCH_DISCOVER_MOVIES";
export const RECEIVE_DISCOVER_MOVIES = "RECEIVE_DISCOVER_MOVIES";
export const FETCH_DISCOVER_TV_SHOWS = "FETCH_DISCOVER_TV_SHOWS";
export const RECEIVE_DISCOVER_TV_SHOWS = "RECEIVE_DISCOVER_TV_SHOWS";
export const ASSIGN_BILLBOARD_MOVIE = "ASSIGN_BILLBOARD_MOVIE";
export const FETCH_BILLBOARD_MOVIE_VIDEOS = "FETCH_BILLBOARD_MOVIE_VIDEOS";
export const RECEIVE_BILLBOARD_MOVIE_VIDEOS = "RECEIVE_BILLBOARD_MOVIE_VIDEOS";
export const SHOW_TRAILER_MODAL = "SHOW_TRAILER_MODAL";

//Search actions
export const CLEAR_SEARCH_TERM = "CLEAR_SEARCH_TERM";
export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
export const UPDATE_SEARCH_BOX_FOCUS = "UPDATE_SEARCH_BOX_FOCUS";
export const FETCH_SEARCH_RESULTS = "FETCH_SEARCH_RESULTS";

//Menu actions
export const TOGGLE_SIDEDRAWER_STATE = "TOGGLE_SIDEDRAWER_STATE";
