//Movie actions
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const FETCH_MOVIE_CREDITS = "FETCH_MOVIE_CREDITS";
export const SET_LOADING = "SET_LOADING";

//Movies actions
export const FETCH_MOVIES_IN_THEATRES = "FETCH_MOVIES_IN_THEATRES";
export const FETCH_MOVIES_POPULAR = "FETCH_MOVIES_POPULAR";
export const FETCH_MOVIES_UPCOMING = "FETCH_MOVIES_UPCOMING";
export const FETCH_MOVIES_TOP_RATED = "FETCH_MOVIES_TOP_RATED";

//TV Shows actions
export const FETCH_TV_SHOWS_ON_TV = "FETCH_TV_SHOWS_ON_TV";
export const FETCH_TV_SHOWS_POPULAR = "FETCH_TV_SHOWS_POPULAR";
export const FETCH_TV_SHOWS_AIRING_TODAY = "FETCH_TV_SHOWS_AIRING_TODAY";
export const FETCH_TV_SHOWS_TOP_RATED = "FETCH_TV_SHOWS_TOP_RATED";

//TV Show actions
export const FETCH_TV_SHOW_DETAILS = "FETCH_TV_SHOW_DETAILS";
export const FETCH_TV_SHOW_CREDITS = "FETCH_TV_SHOW_CREDITS";

//Window actions
export const UPDATE_WINDOW_STATE = "UPDATE_WINDOW_STATE";
export const DETECT_MOBILE = "DETECT_MOBILE";

//Discover actions
export const FETCH_DISCOVER_MOVIES = "FETCH_DISCOVER_MOVIES";
export const FETCH_DISCOVER_TV_SHOWS = "FETCH_DISCOVER_TV_SHOWS";
export const FETCH_BILLBOARD_VIDEOS = "FETCH_BILLBOARD_VIDEOS";

//Search actions
export const CLEAR_SEARCH_TERM = "CLEAR_SEARCH_TERM";
export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
export const UPDATE_SEARCH_BOX_FOCUS = "UPDATE_SEARCH_BOX_FOCUS";
export const FETCH_SEARCH_RESULTS = "FETCH_SEARCH_RESULTS";
